<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnzebix\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnzebix/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVnzebix.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVnzebix\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVnzebix\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vnzebix',
    'container.build_id' => '065e45fd',
    'container.build_time' => 1543171779,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnzebix');
